### ISSUE TITLE
在ios12.1上调试时遇到错误

### ISSUE THREAD

**Issue by haol666** [linguitang/flutter_baidu_map#1]
start loc!
BMKLocationKit has received location
flutter: 签到时间:2018-04-21 00:00:00.000.toString()
签退时间:2018-04-21 00:00:00.000.toString()
	[C3.1.1 51EF9EA3-2855-4ECA-A6C9-C34255464F36 192.168.1.64:59232<->180.97.104.187:443]
	Connected Path: satisfied (Path is satisfied), interface: en3
	Duration: 0.281s, DNS @0.054s took 0.004s, TCP @0.068s took 0.026s, TLS took 0.135s
	bytes in/out: 4632/1069, packets in/out: 11/4, rtt: 0.024s, retransmitted packets: 0, out-of-order packets: 0
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001061c61bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010507d735 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001061124ec _CFThrowFormattedException + 194
	3   CoreFoundation                      0x0000000106235541 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 321
	4   CoreFoundation                      0x00000001061c1c9b +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
	5   Runner                              0x0000000102143285 -[FlutterBaiduMapPlugin location2map:] + 1301
	6   Runner                              0x00000001021436e5 __44-[FlutterBaiduMapPlugin getCurrentLocation:]_block_invoke + 421
	7   Runner                              0x0<…>
Lost connection to device.

**Comment by haol666** [comment]
start loc!
BMKLocationKit has received location
	[C3.1.1 51EF9EA3-2855-4ECA-A6C9-C34255464F36 192.168.1.64:59232<->180.97.104.187:443]
	Connected Path: satisfied (Path is satisfied), interface: en3
	Duration: 0.281s, DNS @0.054s took 0.004s, TCP @0.068s took 0.026s, TLS took 0.135s
	bytes in/out: 4632/1069, packets in/out: 11/4, rtt: 0.024s, retransmitted packets: 0, out-of-order packets: 0
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001061c61bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010507d735 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001061124ec _CFThrowFormattedException + 194
	3   CoreFoundation                      0x0000000106235541 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 321
	4   CoreFoundation                      0x00000001061c1c9b +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
	5   Runner                              0x0000000102143285 -[FlutterBaiduMapPlugin location2map:] + 1301
	6   Runner                              0x00000001021436e5 __44-[FlutterBaiduMapPlugin getCurrentLocation:]_block_invoke + 421
	7   Runner                              0x0<…>
Lost connection to device.

**Comment by linguitang** [comment]
你先排除一下看是不是配置的问题，我之前上传这份代码的时候，我的ios也还是12.1，最近几天手机才升到12.2

**Comment by haol666** [comment]
我的手机现在是12.1.1 beta，Xcode10.1不支持调试。
上面的崩溃信息是通过simulator抓出来的。位置用的是模拟器预置的apple。
对代码增加异常处理：
                @try {
                    NSDictionary *dict = [self location2map:location];
                    NSLog(@"%@", dict);
                    result(dict);
                }
                @catch (NSException *exception) { 
                        NSLog(@"error:%@", exception);
                        @throw exception;
                }
得到错误：*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[7]
此时程序不在崩溃，定位提示定位中。
打印location2map中的参数：
country：United States
countryCode：54003
province：California
city：Cupertino
cityCode：61019
district：(null)
street：North De Anza Boulevard
locationDescribe：
adCode：(null)
isInChina：0
errorCode：161
返回值存在空值。经纬度切到国内，问题解决。
另外在频繁操作获取经纬度的时候发现过经纬度为0.0，locationDescribe正确的情况，估计是百度的问题。

**Comment by linguitang** [comment]
嗯，这个应该是百度的问题
