### ISSUE TITLE
友盟捕获到的崩溃信息，偶现，非必现，显示在getCurrentLocation:location2map中出错了

### ISSUE THREAD

**Issue by githubwp** [linguitang/flutter_baidu_map#3]
Crash reason: EXC_SOFTWARE / UNCAUGHT_NS_EXCEPTION
Thread 0 (crashed)
0 CoreFoundation + 0x11827C
1 libobjc.A.dylib + 0x59F4
2 CoreFoundation + 0x91CE4
3 CoreFoundation + 0x199A4
4 CoreFoundation + 0xA580
5 Runner!-[FlutterBaiduMapPlugin location2map:] [FlutterBaiduMapPlugin.m : 44]
6 Runner!__44-[FlutterBaiduMapPlugin getCurrentLocation:]_block_invoke [FlutterBaiduMapPlugin.m : 76]
7 Runner!__35-[BMKLocationManager excuteNetLoc:]_block_invoke_2 [BMKLocationManager.mm : 1211]
8 libdispatch.dylib + 0x5FA34
9 libdispatch.dylib + 0x607D0
10 libdispatch.dylib + 0xE000
11 CoreFoundation + 0xA9C18
12 CoreFoundation + 0xA4B50
13 CoreFoundation + 0xA40AC
14 GraphicsServices + 0xA798
15 UIKitCore + 0x8BC974
16 Runner!main [main.m : 5]
17 libdyld.dylib + 0x18DC

**Comment by linguitang** [comment]
是真机吗？

**Comment by githubwp** [comment]
对，是真机

**Comment by linguitang** [comment]
会闪退吗
